# Generated by Django 4.0.4 on 2022-07-11 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('link', models.URLField(max_length=128, unique=True)),
                ('paths', models.JSONField()),
                ('javascript', models.BooleanField(default=False)),
                ('regex', models.CharField(max_length=512)),
                ('headline', models.JSONField()),
                ('body', models.JSONField(blank=True, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.language')),
                ('publication_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.publicationtype')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('link', models.URLField(unique=True)),
                ('pubdate', models.DateTimeField()),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.language')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.source')),
            ],
            options={
                'ordering': ('-pubdate',),
            },
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['link'], name='articles_so_link_82283c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['headline', 'link'], name='articles_ar_headlin_b3b21f_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('headline', 'source'), name='unique headline'),
        ),
    ]
