# Generated by Django 4.2.4 on 2023-09-16 10:23

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the source",
                        max_length=128,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="The slug of the source for SEO-friendly urls",
                        verbose_name="Slug",
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[("newspaper/journal", "Newspaper or journal")],
                        help_text="The type of publication of the source",
                        max_length=24,
                        verbose_name="publication type",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English")],
                        help_text="The language of the article",
                        max_length=4,
                        verbose_name="language",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="The link to the source",
                        unique=True,
                        validators=[django.core.validators.URLValidator],
                        verbose_name="link",
                    ),
                ),
                (
                    "paths",
                    models.JSONField(
                        help_text="A list of resource paths where the scraper will look for articles",
                        verbose_name="paths",
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        blank=True,
                        help_text="Regular expression for filtering hyper-links found at the resource paths",
                        max_length=512,
                        verbose_name="regex",
                    ),
                ),
                (
                    "javascript",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the parsing of articles by this source requires rendering of JavaScript",
                        verbose_name="render javascript",
                    ),
                ),
                (
                    "headline_selectors",
                    models.JSONField(
                        help_text="Information about the structure of the target page needed to extract the headline of articles published by this source",
                        verbose_name="headline selectors",
                    ),
                ),
                (
                    "body_selectors",
                    models.JSONField(
                        blank=True,
                        help_text="Information about the structure of the target page needed to extract the body of articles published by this source",
                        null=True,
                        verbose_name="body selectors",
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.TextField(
                        help_text="The headline of the article", verbose_name="headline"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug of the article for SEO-friendly urls",
                        verbose_name="Slug",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English")],
                        help_text="The language of the article",
                        max_length=4,
                        verbose_name="language",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="The link to the article",
                        unique=True,
                        verbose_name="link",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="The body of the article",
                        null=True,
                        verbose_name="body",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source where the article is published",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="articles.source",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["headline", "link"],
                        name="articles_ar_headlin_b3b21f_idx",
                    )
                ],
            },
        ),
    ]
