# Generated by Django 5.0.1 on 2024-03-03 10:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": [django.db.models.functions.text.Lower("title")]},
        ),
        migrations.AlterField(
            model_name="article",
            name="headline",
            field=models.CharField(
                help_text="The headline of the article", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                help_text="The slug of the article for SEO-friendly urls",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(
                help_text="The link to the article", max_length=512, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="summary_search_params_find",
            field=models.JSONField(
                default=str,
                help_text="Selectors for extracting the summary of articles",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="summary_search_params_remove",
            field=models.JSONField(
                default=list,
                help_text="Selectors for HTML elements that need to be removed from the summary",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(
                help_text="The url of the source", max_length=512, unique=True
            ),
        ),
    ]
