# Generated by Django 4.0.4 on 2022-07-26 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='source',
            name='articles_so_link_82283c_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.TextField(unique=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.TextField(unique=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
