[tool.mypy]
python_version = 3.11
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports=true

[tool.django-stubs]
django_settings_module = "config.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"

[tool.pytype]
python_version = 3.11
inputs = ["src/articles/management", "src/articles/scraper", "src/articles/*.py"]
disable = "import-error"
