# Generated by Django 4.2 on 2024-05-19 14:23

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The name of the source", max_length=128, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="The slug of the source for SEO-friendly urls",
                        max_length=255,
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[("newspaper/journal", "Newspaper or journal")],
                        help_text="The type of publication of the source",
                        max_length=24,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English"), ("en-us", "English (AE)")],
                        help_text="The language of the article",
                        max_length=16,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The url of the source", max_length=512, unique=True
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("title")],
            },
        ),
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paths",
                    models.JSONField(
                        help_text="List of resource paths where the scraper will look for articles"
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        blank=True,
                        help_text="Regular expression for filtering hyper-links found at the resource paths",
                        max_length=255,
                    ),
                ),
                (
                    "javascript_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the parsing of articles by this source requires rendering of JavaScript",
                    ),
                ),
                (
                    "headline_search_params_find",
                    models.JSONField(
                        default=str,
                        help_text="Selectors for extracting the headline of articles",
                    ),
                ),
                (
                    "headline_search_params_remove",
                    models.JSONField(
                        blank=True,
                        help_text="Selectors (optional) for HTML elements that need to be removed from the headline",
                        null=True,
                    ),
                ),
                (
                    "summary_search_params_find",
                    models.JSONField(
                        default=str,
                        help_text="Selectors for extracting the summary of articles",
                    ),
                ),
                (
                    "summary_search_params_remove",
                    models.JSONField(
                        blank=True,
                        help_text="Selectors (optional) for HTML elements that need to be removed from the summary",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The url of the RSS feed", max_length=512, unique=True
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds",
                        to="articles.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="The headline of the article", max_length=512
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug of the article for SEO-friendly urls",
                        max_length=1024,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A description/summary of the article"
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("en-us", "English (AE)")],
                        help_text="The language of the article",
                        max_length=16,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The link to the article", max_length=512, unique=True
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source where the article is published",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="articles.source",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["headline", "url"], name="articles_ar_headlin_4f6c91_idx"
            ),
        ),
    ]
