# Generated by Django 4.2 on 2024-05-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="articles_ar_headlin_4f6c91_idx",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="headline",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="sitemap",
            name="headline_search_params_remove",
            field=models.JSONField(
                blank=True,
                help_text="Selectors for HTML elements that need to be removed from the headline",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitemap",
            name="summary_search_params_remove",
            field=models.JSONField(
                blank=True,
                help_text="Selectors for HTML elements that need to be removed from the summary",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["title", "url"], name="articles_ar_title_d381e6_idx"
            ),
        ),
    ]
