# Generated by Django 4.2 on 2024-05-20 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_remove_article_articles_ar_headlin_4f6c91_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitemap",
            old_name="headline_search_params_find",
            new_name="title_search_params_find",
        ),
        migrations.RenameField(
            model_name="sitemap",
            old_name="headline_search_params_remove",
            new_name="title_search_params_remove",
        ),
    ]
