# Generated by Django 4.2 on 2024-04-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_source_options_alter_article_headline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paths",
                    models.JSONField(
                        help_text="List of resource paths where the scraper will look for articles"
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        blank=True,
                        help_text="Regular expression for filtering hyper-links found at the resource paths",
                        max_length=255,
                    ),
                ),
                (
                    "javascript_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the parsing of articles by this source requires rendering of JavaScript",
                    ),
                ),
                (
                    "headline_search_params_find",
                    models.JSONField(
                        help_text="Selectors for extracting the headline of articles"
                    ),
                ),
                (
                    "headline_search_params_remove",
                    models.JSONField(
                        help_text="Selectors for HTML elements that need to be removed from the headline"
                    ),
                ),
                (
                    "summary_search_params_find",
                    models.JSONField(
                        default=str,
                        help_text="Selectors for extracting the summary of articles",
                    ),
                ),
                (
                    "summary_search_params_remove",
                    models.JSONField(
                        default=list,
                        help_text="Selectors for HTML elements that need to be removed from the summary",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The url of the RSS feed", max_length=512, unique=True
                    ),
                ),
                (
                    "use_guid",
                    models.BooleanField(
                        default=False,
                        help_text="Use guid field for retrieving link (default: 'link')",
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        help_text="Format string for converting str to datetime",
                        max_length=64,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Map with information for retrieving RSS feed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rss_feeds",
                        to="articles.source",
                    ),
                ),
            ],
        ),
    ]
