# Generated by Django 4.2 on 2024-04-29 18:18

from django.db import migrations


def migrate_from_source_to_sitemap(apps, schema_editor):
    Source = apps.get_model("articles", "Source")
    Sitemap = apps.get_model("articles", "Sitemap")

    sources = Source.objects.all()

    for source in sources:
        sitemap = Sitemap(
            source=source,
            paths=source.paths,
            regex=source.regex,
            javascript_required=source.javascript_required,
            headline_search_params_find=source.headline_search_params_find,
            headline_search_params_remove=source.headline_search_params_remove,
            summary_search_params_find=source.summary_search_params_find,
            summary_search_params_remove=source.summary_search_params_remove,
        )
        sitemap.save()


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_sitemap_rssfeed"),
    ]

    operations = [migrations.RunPython(migrate_from_source_to_sitemap)]
