# Generated by Django 4.2 on 2024-05-20 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "articles",
            "0003_rename_headline_search_params_find_sitemap_title_search_params_find_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitemap",
            old_name="summary_search_params_find",
            new_name="description_search_params_find",
        ),
        migrations.RenameField(
            model_name="sitemap",
            old_name="summary_search_params_remove",
            new_name="description_search_params_remove",
        ),
    ]
