"""A datapool that contains `sitemaps` with information about the webpages targeted
for scraping; in particular, information concerning the HTML and CSS structure used
by the scraper."""

sitemaps = [
    {
        "name": "Al Jazeera",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.aljazeera.com/",
        "paths": ["news/"],
        "javascript": False,
        "regex": "/[0-9]{4}/[0-9]+/[0-9]+/(?!.*terms-and-conditions/|.*community-rules-guidelines/|.*eu-eea-regulatory|.*code-of-ethics)",
        "headline": {"tag": "h1", "attrs": {}},
        "body": {"tag": "p", "attrs": {"class": "article__subhead"}},
    },
    {
        "name": "Associated Press",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://apnews.com/",
        "paths": ["hub/world-news/", "hub/business/"],
        "javascript": False,
        "regex": "article/",
        "headline": {"tag": "h1", "attrs": {}},
        "body": {"tag": "div", "attrs": {"class": "Article"}},
    },
    {
        "name": "Christian Science Monitor",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.csmonitor.com/",
        "paths": ["world/", "USA/"],
        "javascript": False,
        "regex": "USA/.*[0-9]{4}/[0-9]{4}/|World/.*[0-9]{4}/[0-9]{4}/",
        "headline": {"tag": "h1", "attrs": {"id": "headline"}},
        "body": {"tag": "div", "attrs": {"class": "story-two"}},
    },
    {
        "name": "Consortium News",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://consortiumnews.com/",
        "paths": [""],
        "javascript": False,
        "regex": "[0-9]{4}/[0-9]{2}/[0-9]{2}/(?!.*contact-us-form/|.*parry-awarded|.*robert-parrys-legacy)[a-z]+(?!.*policy)(?!.*live)(?!.*fund-drive)",
        "headline": {"tag": "h1", "attrs": {}},
        "body": {"tag": "p", "attrs": {}},
    },
    {
        "name": "Current Affairs",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.currentaffairs.org/",
        "paths": ["category/politics/", "category/economics", "category/interviews", "category/history"],
        "javascript": False,
        "regex": "[0-9]{4}/[0-9]{2}/",
        "headline": {"tag": "h1", "attrs": {"class": "title"}},
        "body": {"tag": "div", "attrs": {"class": "tagline"}},
    },
    {
        "name": "New York Times",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.nytimes.com/",
        "paths": ["section/world/", "section/business/"],
        "javascript": False,
        "regex": "(?<!/es/)(?<!/live/)[0-9]{4}/[0-9]{2}/[0-9]{2}/",
        "headline": {"tag": "h1", "attrs": {"data-testid": "headline"}},
        "body": {"tag": "section", "attrs": {"class": "meteredContent"}},
    },
    {
        "name": "NPR",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.npr.org/",
        "paths": ["sections/world/"],
        "javascript": False,
        "regex": "/[0-9]{4}/[0-9]{2}/[0-9]{2}/",
        "headline": {"tag": "h1", "attrs": {}},
        "body": None,
    },
    {
        "name": "Reuters",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.reuters.com/",
        "paths": ["world/"],
        "javascript": True,
        "regex": "[0-9]{4}-[0-9]{2}-[0-9]{2}/$",
        "headline": {"tag": "h1", "attrs": {}},
        "body": {"tag": "p", "attrs": {"data-testid": "paragraph-0"}},
    },
    {
        "name": "The Atlantic",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.theatlantic.com/",
        "paths": ["international/", "politics/", "business/"],
        "javascript": False,
        "regex": "archive/[0-9]{4}/",
        "headline": {"tag": "h1", "attrs": {}},
        "body": {"tag": "section", "attrs": {"class": "ArticleBody_root__nZ4AR"}},
    },
    {
        "name": "The Intercept",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://theintercept.com/",
        "paths": ["world/", "politics/"],
        "javascript": False,
        "regex": "[0-9]{4}/[0-9]{2}/[0-9]{2}",
        "headline": {"tag": "h1", "attrs": {}},
        "body": {"tag": "h2", "attrs": {}},
    },
    {
        "name": "UPI",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.upi.com/",
        "paths": ["Top_News/World-News/"],
        "javascript": False,
        "regex": "[0-9]{4}/[0-9]{2}/[0-9]{2}/",
        "headline": {"tag": "h1", "attrs": {}},
        "body": {"tag": "article", "attrs": {}},
    },
    {
        "name": "Wall Street Journal",
        "publication_type": "newspaper/journal",
        "language": "en",
        "base_url": "https://www.wsj.com/",
        "paths": ["news/world/"],
        "javascript": False,
        "regex": "articles/(?!.*comments_sector)",
        "headline": {"tag": "h1", "attrs": {}},
        "body": None,
    },
]
